/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as HomeConnectivityRouteImport } from './routes/home-connectivity'
import { Route as InternetServicesRouteImport } from './routes/internet-services'
import { Route as LearningCenterRouteImport } from './routes/learning-center'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TvStreamingRouteImport } from './routes/tv-streaming'
import { Route as WirelessRouteImport } from './routes/wireless'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeConnectivityRoute = HomeConnectivityRouteImport.update({
  id: '/home-connectivity',
  path: '/home-connectivity',
  getParentRoute: () => rootRouteImport,
} as any)
const InternetServicesRoute = InternetServicesRouteImport.update({
  id: '/internet-services',
  path: '/internet-services',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCenterRoute = LearningCenterRouteImport.update({
  id: '/learning-center',
  path: '/learning-center',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TvStreamingRoute = TvStreamingRouteImport.update({
  id: '/tv-streaming',
  path: '/tv-streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const WirelessRoute = WirelessRouteImport.update({
  id: '/wireless',
  path: '/wireless',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/home-connectivity': typeof HomeConnectivityRoute
  '/internet-services': typeof InternetServicesRoute
  '/learning-center': typeof LearningCenterRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tv-streaming': typeof TvStreamingRoute
  '/wireless': typeof WirelessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/home-connectivity': typeof HomeConnectivityRoute
  '/internet-services': typeof InternetServicesRoute
  '/learning-center': typeof LearningCenterRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tv-streaming': typeof TvStreamingRoute
  '/wireless': typeof WirelessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/home-connectivity': typeof HomeConnectivityRoute
  '/internet-services': typeof InternetServicesRoute
  '/learning-center': typeof LearningCenterRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tv-streaming': typeof TvStreamingRoute
  '/wireless': typeof WirelessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/home-connectivity'
    | '/internet-services'
    | '/learning-center'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/tv-streaming'
    | '/wireless'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/home-connectivity'
    | '/internet-services'
    | '/learning-center'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/tv-streaming'
    | '/wireless'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/home-connectivity'
    | '/internet-services'
    | '/learning-center'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/tv-streaming'
    | '/wireless'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  HomeConnectivityRoute: typeof HomeConnectivityRoute
  InternetServicesRoute: typeof InternetServicesRoute
  LearningCenterRoute: typeof LearningCenterRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TvStreamingRoute: typeof TvStreamingRoute
  WirelessRoute: typeof WirelessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-connectivity': {
      id: '/home-connectivity'
      path: '/home-connectivity'
      fullPath: '/home-connectivity'
      preLoaderRoute: typeof HomeConnectivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internet-services': {
      id: '/internet-services'
      path: '/internet-services'
      fullPath: '/internet-services'
      preLoaderRoute: typeof InternetServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-center': {
      id: '/learning-center'
      path: '/learning-center'
      fullPath: '/learning-center'
      preLoaderRoute: typeof LearningCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-streaming': {
      id: '/tv-streaming'
      path: '/tv-streaming'
      fullPath: '/tv-streaming'
      preLoaderRoute: typeof TvStreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireless': {
      id: '/wireless'
      path: '/wireless'
      fullPath: '/wireless'
      preLoaderRoute: typeof WirelessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  HomeConnectivityRoute: HomeConnectivityRoute,
  InternetServicesRoute: InternetServicesRoute,
  LearningCenterRoute: LearningCenterRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TvStreamingRoute: TvStreamingRoute,
  WirelessRoute: WirelessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
